### ISSUE TITLE
ISTA4.46.14 run Error

### ISSUE THREAD

**Issue by renzhig** [tautcony/ISTA-Patcher#20] opened 2024-03-03 14:53 UTC
**Describe the bug**

ISTA4.46.14 Err.
Failed to start lSTA
Please make sure your ISTA configuration is valid.In doubt reset any non standard lSTA configuration and reinstallISTA

**To Reproduce**
1.Use ISTA-Patcher2.1.1  PATCH to replace files and run
2. See error

**Screenshots**
![微信截图_20240303214501](https://github.com/tautcony/ISTA-Patcher/assets/86832816/4700bc87-ca95-4cc5-b618-b48c23cb2c9e)

**Logs**
If applicable, upload logs under `ISTA\Logs` to help troubleshoot your problem (emptying the `Logs` folder and reproducing the problem before uploading them would be more helpful in analyzing the logs).
[20240303_214254_21bb7ddf-34de-4aea-ae1b-e35ed17151a2_IstaServicesHost.log](https://github.com/tautcony/ISTA-Patcher/files/14473386/20240303_214254_21bb7ddf-34de-4aea-ae1b-e35ed17151a2_IstaServicesHost.log)
[20240303_DESKTOP-0CCGV0H_ISTA.log](https://github.com/tautcony/ISTA-Patcher/files/14473387/20240303_DESKTOP-0CCGV0H_ISTA.log)

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 22H1]
 - ISTA Version [e.g. 4.46.14]
 - ISTA Edition [e.g. standalone]

**Additional context**
https://mega.nz/file/N0hy2JiD#Z6MYXaisyGwETnfNfJt0Rs5FSSupBj6DWpSOIDV2KRU
Installation files for ISTA4.46.14

**Comment by iggy2022** [comment] 2024-03-03 19:35
hello
![1](https://github.com/tautcony/ISTA-Patcher/assets/105745715/fbeaf136-3f98-40d8-996b-7eeac4926cb3)

**Comment by iggy2022** [comment] 2024-03-03 19:37
I can't reproduce your problem

**Comment by tautcony** [comment] 2024-03-04 04:08
> I can't reproduce your problem

The original MSI package requires extra editing to make it installable, or simply extracting files directly from the MSI package.

**Comment by renzhig** [comment] 2024-03-04 04:21
> > 我无法重现你的问题
> 
> 原始 MSI 包需要额外的编辑才能安装，或者直接从 MSI 包中提取文件。

I can provide any additional documents you need

**Comment by renzhig** [comment] 2024-03-04 04:22
I can provide any additional documents you need

> > I can't reproduce your problem
> 
> The original MSI package requires extra editing to make it installable, or simply extracting files directly from the MSI package.

I can provide any additional documents you need

**Comment by tautcony** [comment] 2024-03-04 04:43
Note that there is a `System.Reflection.ReflectionTypeLoadException` in the log, along with the error stack. Some new code is trying to serialize an object, but seems to be missing the `IRefreshTokenJob` type, I 'm not sure with assembly would include this type, may need more infomation.

**Comment by renzhig** [comment] 2024-03-04 04:46
> Note that there is a `System.Reflection.ReflectionTypeLoadException` in the log, along with the error stack. Some new code is trying to serialize an object, but seems to be missing the `IRefreshTokenJob` type, I 'm not sure with assembly would include this type, may need more infomation.

Do you need me to do anything now?

**Comment by tautcony** [comment] 2024-03-04 05:31
> > Note that there is a `System.Reflection.ReflectionTypeLoadException` in the log, along with the error stack. Some new code is trying to serialize an object, but seems to be missing the `IRefreshTokenJob` type, I 'm not sure with assembly would include this type, may need more infomation.
> 
> Do you need me to do anything now?

Not yet, just saying there's not enough information right now.

**Comment by Sackret** [comment] 2024-03-06 13:44
Hello, if you need help, tell me that error is because not everything in the msi has been decompressed properly. I could solve the problems, it is very easy to remove everything from an msi....
and the error in the friend's photo is because it has an error in some file that has not been patched.....

This is another matter, I have already found out everything about it that we talk about on Discord, I have already figured out how they do that, I have created several...

**Comment by Sackret** [comment] 2024-03-06 17:06
but I don't know that you don't change the ista cfg? and the errors disappear, change the cfg for the rheingold version and that's it, the version would work

**Comment by renzhig** [comment] 2024-03-07 01:49
I see that this file "CommonServices. DLL" controls the generation. This file was obtained from a crack done by someone else
[CommonServices.zip](https://github.com/tautcony/ISTA-Patcher/files/14517605/CommonServices.zip)。But after replacing this file, the software can only open and query normally, and there is still a problem with the diagnosis

**Comment by renzhig** [comment] 2024-03-07 02:06
This log is the entire process from opening the software to diagnosing errors and then closing the software, DebugView The LOG file is recorded by the DebugView software during the diagnostic process, and the other log.zip is the log of the ISTA software during the diagnostic process
[DebugView.LOG](https://github.com/tautcony/ISTA-Patcher/files/14517748/DebugView.LOG)
[Logs.zip](https://github.com/tautcony/ISTA-Patcher/files/14517749/Logs.zip)

**Comment by renzhig** [comment] 2024-03-07 02:29
This log is the entire process from opening the software to diagnosing errors and then closing the software, DebugView The LOG file is recorded by the DebugView software during the diagnostic process, and the other log.zip is the log of the ISTA software during the diagnostic process
[DebugView.LOG](https://github.com/tautcony/ISTA-Patcher/files/14517902/DebugView.LOG)
[Logs.zip](https://github.com/tautcony/ISTA-Patcher/files/14517903/Logs.zip)

**Comment by tautcony** [comment] 2024-03-07 03:30
```log
00001578	200.14562988	[8660] 2024-03-07 10:22:14.400 INFO [T] ISTA: [17] VehicleIdent.doMissingECUIdent - trying to identify still unknown ECU at address: 67 	
00001579	200.14575195	[8660] 2024-03-07 10:22:14.400 WARNING [T] ISTA: [17] VehicleIdent.doMissingECUIdent - no ecu group available; no info available for ecu: 67 /  	
00001580	200.14602661	[8660] 2024-03-07 10:22:14.400 INFO [T] ISTA: [17] VehicleIdent.ForcePhysicalIdentOnUnindentified - ECU with SGBD:  and address: 0x67 did not respond to IDENT jobs. 	  	

...

00001627	237.81570435	[8660] 2024-03-07 10:22:52.069 WARNING [T] ISTA: [17] VehicleDataConverter.FindEcuVariantFromBntn - More than one ECU variants found [flm02_l,flm02x_l] for 'FLM-02-LINKS' 	
00001628	237.81724548	[8660] 2024-03-07 10:22:52.071 WARNING [T] ISTA: [17] VehicleDataConverter.GetEcuVariantByName - No ECU variant found for 'FLM-02-LINKS' and no diag address '67' 	
00001629	237.81800842	[8660] 2024-03-07 10:22:52.072 WARNING [T] ISTA: [17] Logic.StartVehicleIdentification - failed with exception: System.NullReferenceException: 未将对象引用设置到对象的实例。 	
00001630	237.81800842	[8660]    在 BMW.Rheingold.Diagnostics.VehicleIdent.<>c__DisplayClass256_0.<AddPSdZEcusToVehicleEcus>b__0(IPsdzEcu x) 	
00001631	237.81800842	[8660]    在 BMW.Rheingold.CoreFramework.Extensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action) 	
00001632	237.81800842	[8660]    在 BMW.Rheingold.Diagnostics.VehicleIdent.AddPSdZEcusToVehicleEcus(Boolean setSvtEcusIntoSvtEcuCollection) 	
00001633	237.81800842	[8660]    在 BMW.Rheingold.Diagnostics.VehicleIdent.StartCalculateSvtFromPsdz(IProgressMonitor monitor, Boolean setSvtEcusIntoSvtEcuCollection) 	
00001634	237.81800842	[8660]    在 BMW.Rheingold.Diagnostics.VehicleIdent.CheckIfEcuHasUnknownEcuGroup(IProgressMonitor monitor) 	
00001635	237.81800842	[8660]    在 BMW.Rheingold.Diagnostics.VehicleIdent.ExecuteEdiabasJobBN2020(IProgressMonitor monitor) 	
00001636	237.81800842	[8660]    在 BMW.Rheingold.Diagnostics.VehicleIdent.ExecuteEdiabasJobsForVehicleIdentification(IProgressMonitor monitor, IKmmService kmmService, DateTime startDate, IFFMDynamicResolver ffmResolver) 	
00001637	237.81800842	[8660]    在 BMW.Rheingold.RheingoldSessionController.Logic.StartVehicleIdentificationWithVehicle(IProgressMonitor monitor) 	
00001638	237.81800842	[8660]    在 BMW.Rheingold.RheingoldSessionController.Logic.StartVehicleIdentification(IProgressMonitor monitor, String& errorText, Boolean forceOldVehicleIdentificationProcess, Boolean comingFromInfosession) 	
00001639	237.81811523	[8660] 2024-03-07 10:22:52.072 INFO [T] ISTA: [17] Vehicle.UpdateStatus() - Change state from '#VehicleIdent/running' to '#UnknownVIN/error' 

...	

00002428	238.07006836	[8660] 2024-03-07 10:22:52.324 WARNING [T] ISTA: [17] Logic.IdentifyVehicle - failed to identify vehicle 	

...

00002462	239.19758606	[8660] 2024-03-07 10:22:52.827 INFO [T] ISTA: [17] InteractionController.RegisterInteractionModel() - A 'InteractionMessageModel' was registered. Interaction Title: '错误 (Powered by ISTA-Patcher 2.1.1)' 	
```

It seems an NPE was thrown during vehicle identification caused by non-responsive ECU, what did the dialog show? I don't know much about the usage for ista, did previous versions report this error?

The dll file is identical with the original one, is the upload correct?

**Comment by renzhig** [comment] 2024-03-07 03:36
There was no such error in previous versions, and all DLL files were created using ISTA Patch except for CommonServices.DLL

**Comment by tautcony** [comment] 2024-03-07 04:15
```log
24-03-07 10:22:06,474 [TCP-Reader-169.254.247.57:6801] [ERROR] [] com.bmw.prodias.io.DefaultCommunicationProcessor: got a communication error with no SA on channel tcp://169.254.247.57:6801, control code= 64, data= 0xFF 0xF4, CAN error="unspecified general error"
24-03-07 10:22:06,640 [TCP-Reader-169.254.247.57:6801] [ERROR] [] com.bmw.prodias.io.DefaultCommunicationProcessor: got a communication error with no SA on channel tcp://169.254.247.57:6801, control code= 64, data= 0xFF 0xF4, CAN error="unspecified general error"
24-03-07 10:22:06,944 [TCP-Reader-169.254.247.57:6801] [ERROR] [] com.bmw.prodias.io.DefaultCommunicationProcessor: got a communication error with no SA on channel tcp://169.254.247.57:6801, control code= 64, data= 0xFF 0xF4, CAN error="unspecified general error"
24-03-07 10:22:07,244 [TCP-Reader-169.254.247.57:6801] [ERROR] [] com.bmw.prodias.io.DefaultCommunicationProcessor: got a communication error with no SA on channel tcp://169.254.247.57:6801, control code= 64, data= 0xFF 0xF4, CAN error="unspecified general error"
24-03-07 10:22:07,518 [TCP-Reader-169.254.247.57:6801] [ERROR] [] com.bmw.prodias.io.DefaultCommunicationProcessor: got a communication error with no SA on channel tcp://169.254.247.57:6801, control code= 64, data= 0xFF 0xF4, CAN error="unspecified general error"
24-03-07 10:22:07,550 [Thread-39] [INFO] [] com.bmw.psdz.jobs.common.MCD3_GenerateConfigFromVehicle: MCD service RDBI_SVK finished
***** Link: PROG_UDS_DF_ETHERNET, Service: RDBI_SVK - ReadDataByIdentifier SVK
Request Parameter count: 2
 - RDBI: 0x22
 - RDBI_DID: SVK_Aktuell
Request PDU: (3) 22 f1 01 
Result error: MCDError Severity: 2051, Error Code: 53327, Description: service execution failed, Vendor Code: 32768, Vendor Description: dispatchEOF called, Interface Error Code: 0x0

Response count: 0
DiagAdresses: 0xf4 -> 0xdf
```

From the available logs, it appears to be a communication error with the vehicle, which should not be caused by the patcher.

> I see that this file "CommonServices. DLL" controls the generation. This file was obtained from a crack done by someone else [CommonServices.zip](https://github.com/tautcony/ISTA-Patcher/files/14517605/CommonServices.zip)。But after replacing this file, the software can only open and query normally, and there is still a problem with the diagnosis

Since CommonServices.DLL is identical to the original, according to what you have uploaded, this file should not be patched and can then be started normally, is that correct?

**Comment by OnSerious** [comment] 2024-03-08 11:07
I think you have some other configuration errors. I got mine running, but i am also new to the whole ISTA Process. Always used standalones. But in lack of them i tried many things the last days with installed istalauncher and without. in lack of a manual i fell over this github repository and took my own way. 

1. Patched Install .msi and installed it without Ista Launcher 
2. Checked Folder Structure - SQLiteDBs and BLP/SDP were somehow not installed. Placed them inside
3. Used Ista-Patcher[Start failed with same error]
4, imported generated license.reg first time  [Start failed with same error]

The problem you maybe have is the IstaGui.exe.config. I somehow opened and edited it, but it also failed to start. so i started with the original ISTAGui.exe.config file, and there is somehow a old standalone of ISTA floating around on the net.

i merged the IstaGui.exe.config with mine from 4.46.14 in the <appSettings></appSettings> part.  I actually dont know which part removes the problem but now it is starting without a problem, can also enter a vin and i get information. but dont have a car here to test at the moment with e-net or icom. 

so at the end i think it is not a bug of the ISTA-Patcher, it is bug of your configuration, or you trying to build a standalone...

**Comment by renzhig** [comment] 2024-03-08 11:19
CommonServices The DLL file is not the original file, it has been modified by someone else. The ISTAGuiexe.config file was also modified by this person.
[ISTAGUI.exe.zip](https://github.com/tautcony/ISTA-Patcher/files/14537408/ISTAGUI.exe.zip)
https://mega.nz/folder/rsBFUSLK#Eta98k4oSyfFxitBl8L14A https://mega.nz/folder/rsBFUSLK#Eta98k4oSyfFxitBl8L14A。
Do you need any other files, including the crack done by another person, that can also be given to you, but their ISTAGUIexe is encrypted

**Comment by OnSerious** [comment] 2024-03-09 00:28
Ok, I now know that also some other file needs to be changed. But dont know which one. I made a standalone version from my installed one and put it in C:\EC-Apps\ISTA. I think this is not the normal use case for this patcher, but without a manual i only know this way. 

My standalone wss starting as long, as the original ISTA Installation was in C:\Programm Files(x86)\BMW folder and the original unmodified files where there.

as soon as i removed the installation with the installer, also my  self created standalone in C:\EC-Apps did not work anymore. So something is looking for the original directory. Maybe your mentioned .dll or some other config file.

**Comment by iggy2022** [comment] 2024-03-09 17:01
> CommonServices The DLL file is not the original file, it has been modified by someone else. The ISTAGuiexe.config file was also modified by this person. [ISTAGUI.exe.zip](https://github.com/tautcony/ISTA-Patcher/files/14537408/ISTAGUI.exe.zip) https://mega.nz/folder/rsBFUSLK#Eta98k4oSyfFxitBl8L14A [https://mega.nz/folder/rsBFUSLK#Eta98k4oSyfFxitBl8L14A。](https://mega.nz/folder/rsBFUSLK#Eta98k4oSyfFxitBl8L14A%E3%80%82) Do you need any other files, including the crack done by another person, that can also be given to you, but their ISTAGUIexe is encrypted

download in progress
no fr_FR ??

**Comment by nickgzz** [comment] 2024-03-13 16:27
Hello all!
I'm facing the same problem trying to start Ista after the patch was applied. I made a standalone of versions 4.45.30, 4.46.14 and 4.46.21. Starting from version 4.46.14 the Ista will not start, followed by the error message: "please make sure your ISTA configuration is  valid". When reverting back to 4.45.30 everything works fine by adapting the "ISTAGUI.exe.config" and registry file to the corresponding version. I'm assuming something changed starting with the version 4.46.14. I have attached the logs from 4.46.21.
[20240313_LATITUDE5521_ISTA.log](https://github.com/tautcony/ISTA-Patcher/files/14590775/20240313_LATITUDE5521_ISTA.log)

**Comment by tautcony** [comment] 2024-03-14 00:39
> Hello all! I'm facing the same problem trying to start Ista after the patch was applied. I made a standalone of versions 4.45.30, 4.46.14 and 4.46.21. Starting from version 4.46.14 the Ista will not start, followed by the error message: "please make sure your ISTA configuration is valid". When reverting back to 4.45.30 everything works fine by adapting the "ISTAGUI.exe.config" and registry file to the corresponding version. I'm assuming something changed starting with the version 4.46.14. I have attached the logs from 4.46.21. [20240313_LATITUDE5521_ISTA.log](https://github.com/tautcony/ISTA-Patcher/files/14590775/20240313_LATITUDE5521_ISTA.log)

```
---> BMW.iLean.CommonServices.Exceptions.CommonServiceException: 0A_ICS0133: CommonserviceException, see inner exception for more details ---> System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=2.0.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Is the installation done by official msi file? it seems that some dependency is missing, you can try to download it and place with the istagui.exe. https://www.nuget.org/packages/log4net/2.0.13

With version 4.16.x, a variety of different reported exceptions appear, not very consistently, I'll collect more log for root cause.

**Comment by nickgzz** [comment] 2024-03-14 00:54
> > Hello all! I'm facing the same problem trying to start Ista after the patch was applied. I made a standalone of versions 4.45.30, 4.46.14 and 4.46.21. Starting from version 4.46.14 the Ista will not start, followed by the error message: "please make sure your ISTA configuration is valid". When reverting back to 4.45.30 everything works fine by adapting the "ISTAGUI.exe.config" and registry file to the corresponding version. I'm assuming something changed starting with the version 4.46.14. I have attached the logs from 4.46.21. [20240313_LATITUDE5521_ISTA.log](https://github.com/tautcony/ISTA-Patcher/files/14590775/20240313_LATITUDE5521_ISTA.log)
> 
> ```
> ---> BMW.iLean.CommonServices.Exceptions.CommonServiceException: 0A_ICS0133: CommonserviceException, see inner exception for more details ---> System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=2.0.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> ```
> 
> Is the installation done by official msi file? it seems that some dependency is missing, you can try to download it and place with the istagui.exe. https://www.nuget.org/packages/log4net/2.0.13
> 
> With version 4.16.x, a variety of different reported exceptions appear, not very consistently, I'll collect more log for root cause.

Yes, the original msi installer was used. Exactly the same steps I used for 4.45.30 and had no issues. I will try to download the missing dependency and will report back.

**Comment by renzhig** [comment] 2024-03-14 03:46
ISTA+ 4.46.2x Install Files - MEGA
https://mega.nz/folder/NwhAkDTZ#t_6m7VGWlQNjFp4AzBJbbw
There have been significant changes to the program starting from ista4.46.1x, and the previous patch may not be applicable.

**Comment by renzhig** [comment] 2024-03-14 13:02
It can be started, but it cannot be checked in the manual or diagnosed

**Comment by nickgzz** [comment] 2024-03-14 15:10
> It can be started, but it cannot be checked in the manual or diagnosed

Mine is working fine on a F34 
<details>
<summary>click to see details</summary>

![identification](https://github.com/tautcony/ISTA-Patcher/assets/155672084/53b2e00f-4645-44e1-91ee-ce1c0c8390e1)
![unit tree](https://github.com/tautcony/ISTA-Patcher/assets/155672084/6b2dc38f-827e-493d-8c30-744fe677049d)
![unit tree cleared](https://github.com/tautcony/ISTA-Patcher/assets/155672084/273db7af-be3f-4b3f-bf8f-7a4e96adf32b)
</details>

**Comment by renzhig** [comment] 2024-03-14 16:32
Can you send me a compressed file of your ISTA so that I can see what the problem is。。 Email: renzhig@outlook.com
Thanks

**Comment by tautcony** [comment] 2024-03-15 02:40
@renzhig The `CommonServices.dll` file is identical to the one extracted from MSI, both in 4.46.14 and 4.46.21, I rechecked and didn't understand exactly what "crack done by someone else" was about.

```
❯ sha1sum CommonServices.dll
12913ac552648187eee48233d4d1e618fffc87bd  CommonServices.dll
❯ sha1sum CommonServices-patched-from-issue.dll
12913ac552648187eee48233d4d1e618fffc87bd  CommonServices-patched-from-issue.dll
```

**Comment by CharlesJung73** [comment] 2024-03-16 11:52
Eureka!

I found a way to fix the "Configurarion is valid" error.

The reason for the error is "C:\ProgramData\BMW\ISPI\config\ILAN\ISPI Admin Client\
This is because the ClientConfiguration.enc" file does not exist.

The ISTA App that is not certified generates the "ClientConfiguration.enc" file, but the ISTA App that is certified does not generate the "ClientConfiguration.enc" file.

The workaround is to run the authentication patch only once to generate the "ClientConfiguration.enc" file.

However, if you apply the "ClientConfiguration.enc" file to another PC, you will not be able to share it with others because "Configurarion is valid" occurs.

It is presumed that the ISTA contains encoded information based on the unique information of the installed PC.

After running an ISTA without an authentication patch, you must restart Windows or force an exit from the isaServicesHost process to avoid errors when applying authentication-patched files.

For your information, I have manually extracted the file from BMW_ISPI_ISTA-APP_4.46.30.27498.msi file, copied it to ISTA folder, applied authentication patch, and modified the version information of the registry.

File extracted from BMW_ISPI_ISTA-APP_4.46.30.27498.msi.

https://mega.nz/folder/ixI2DADY#XnU-RoniuR1rveRQWq6kUQ

**Comment by iggy2022** [comment] 2024-03-16 12:16
congratulations for your analysis !!
good job

**Comment by CharlesJung73** [comment] 2024-03-16 18:00
I applied the patch except for the "CommonServices.dll" file, and the "ClientConfiguration.enc" file is created, and ISTA runs normally.

However, I haven't connected to the vehicle and tested it yet, so I haven't tested the vehicle diagnosis or whether the "Execute Measures Plan" button is activated.

I will check it later when I have time.

Anyway, I think the "CommonServices.dll" file is the key to troubleshooting.

**Comment by OnSerious** [comment] 2024-03-16 19:09
I‘m actually not at home, but renzhig posted a CommonServices.dll which is from the cracked/patched version. Tautcony checked both, and told it is identical file. Maybe there was a file confusement or ISTA Installation is placing another file.

I somehow remember, i opened the original one and the patched one he posted with 7-Zip. There is a version.txt inside which have the same version value. But compared with hex editor there are many changed values. After that I opened up both files with IDA Pro, and it looks like, that there is a part deleted, and many loading loc parts showing different hex locations, maybe because of the deleted part.

I am not experienced in .NET Programming so I don’t understand if it is only the deleted part what changed Everything there.

I installed with patched .msi then moved ISTA Folder from standard Folder to another place. I patched with patcher and it started but did not test diag. After I removed ISTA in Windows Settings / Apps, it was not working anymore (wrong config) till I put the CommonServices.dll from renzhig. I also noticed the removed programdata/bmw folder after removing ista from Settings/Apps and the recreation of the programdata/bmw folder when it started again. So maybe we are also on the right way with the .enc file.

**Comment by tautcony** [comment] 2024-03-17 14:03
> I applied the patch except for the "CommonServices.dll" file, and the "ClientConfiguration.enc" file is created, and ISTA runs normally.
> 
> However, I haven't connected to the vehicle and tested it yet, so I haven't tested the vehicle diagnosis or whether the "Execute Measures Plan" button is activated.
> 
> I will check it later when I have time.
> 
> Anyway, I think the "CommonServices.dll" file is the key to troubleshooting.

Could you please upload both two versions of CommonServices.dll, I would like to check the difference between these two files.

If ISTA could run without the contents of ClientConfiguration, A new option has been added to skip that check before loading, fully untested (there are some ci issue now, I would fix that later).

**Comment by renzhig** [comment] 2024-03-17 14:13
> > I applied the patch except for the "CommonServices.dll" file, and the "ClientConfiguration.enc" file is created, and ISTA runs normally.
> > However, I haven't connected to the vehicle and tested it yet, so I haven't tested the vehicle diagnosis or whether the "Execute Measures Plan" button is activated.
> > I will check it later when I have time.
> > Anyway, I think the "CommonServices.dll" file is the key to troubleshooting.
> 
> Could you please upload both two versions of CommonServices.dll, I would like to check the difference between these two files.
> 
> If ISTA could run without the contents of ClientConfiguration, A new option has been added to skip that check before loading, fully untested (there are some ci issue now, I would fix that later).

[Uploading CommonServices 4.46.14.zip…]()

**Comment by CharlesJung73** [comment] 2024-03-17 15:18
> > I applied the patch except for the "CommonServices.dll" file, and the "ClientConfiguration.enc" file is created, and ISTA runs normally.
> > However, I haven't connected to the vehicle and tested it yet, so I haven't tested the vehicle diagnosis or whether the "Execute Measures Plan" button is activated.
> > I will check it later when I have time.
> > Anyway, I think the "CommonServices.dll" file is the key to troubleshooting.
> 
> Could you please upload both two versions of CommonServices.dll, I would like to check the difference between these two files.
> 
> If ISTA could run without the contents of ClientConfiguration, A new option has been added to skip that check before loading, fully untested (there are some ci issue now, I would fix that later).



> > I applied the patch except for the "CommonServices.dll" file, and the "ClientConfiguration.enc" file is created, and ISTA runs normally.
> > However, I haven't connected to the vehicle and tested it yet, so I haven't tested the vehicle diagnosis or whether the "Execute Measures Plan" button is activated.
> > I will check it later when I have time.
> > Anyway, I think the "CommonServices.dll" file is the key to troubleshooting.
> 
> Could you please upload both two versions of CommonServices.dll, I would like to check the difference between these two files.
> 
> If ISTA could run without the contents of ClientConfiguration, A new option has been added to skip that check before loading, fully untested (there are some ci issue now, I would fix that later).

ISTA 4.46.30.27498
CommonServices.dll

https://mega.nz/folder/ixI2DADY#XnU-RoniuR1rveRQWq6kUQ

**Comment by CharlesJung73** [comment] 2024-03-20 05:33
I tested it in my vehicle yesterday.

Diagnostics and error deletion were performed successfully and the "Execute Measures Plan" button was activated. ^^v

**Closed** 2024-04-07 13:02 UTC
Labels: good first issue, question

**Comment by BMW-FANS** [comment] 2024-04-29 05:53
"Execute Measures Plan" What are the steps to activate?
