### ISSUE TITLE
Failed to start ISTA.

### ISSUE THREAD

**Issue by xanbcom** [tautcony/ISTA-Patcher#24] opened 2024-07-22 16:47 UTC
Failed to start ISTA.
Please make sure your ISTA configuration is valid.
In doubt reset any non standard ISTA configuration and reinstall ISTA.

ISTA4.48.20.28268  ISTA4.48.30.28287  Fail.
ISTA4.48.14.28244 normal.

**Comment by CharlesJung73** [comment] 2024-07-22 23:22
Patch to version 2.3.0.

The error is no longer available.

Thank you @tautcony  :)

**Comment by tautcony** [comment] 2024-07-23 02:32
> Failed to start ISTA. Please make sure your ISTA configuration is valid. In doubt reset any non standard ISTA configuration and reinstall ISTA.
> 
> ISTA4.48.20.28268 ISTA4.48.30.28287 Fail. ISTA4.48.14.28244 normal.

More detail required, please fill the issue template and provided related infomation.

**Comment by xanbcom** [comment] 2024-07-23 15:31
> > Failed to start ISTA. Please make sure your ISTA configuration is valid. In doubt reset any non standard ISTA configuration and reinstall ISTA.
> > ISTA4.48.20.28268 ISTA4.48.30.28287 Fail. ISTA4.48.14.28244 normal.
> 
> More detail required, please fill the issue template and provided related infomation.

[ISTAGUI.exe.config.txt](https://github.com/user-attachments/files/16351124/ISTAGUI.exe.config.txt)

ISTA4.48.30.28287  ISTAGUI.exe.config

**Comment by CharlesJung73** [comment] 2024-07-24 00:09
I only saw the error message and knew if there was a problem with the "ISTAGUI.exe.config" file.

However, the cause of the problem was that there were no 2 files created in the "C:\ProgramData\BMW\ISPI\config\ILIAN\ISPI Admin Client\" folder.

First, check if you have two files: "ClientConfiguration.enc" and "ClientConfiguration.xml".

If the file still has the same error, it will be fixed by patching it to version 2.3.0.

**Comment by xanbcom** [comment] 2024-07-25 16:19
I use the same patch process, ISTA4.48.14.28244 can be patched successfully, but ISTA4.48.20.28268 and ISTA4.48.30.28287 cannot be patched successfully?  
Does version 2.3.0 require any options?

**Comment by xanbcom** [comment] 2024-07-25 17:32
tautcony，Many thanks！   --patch-user-auth option  Successfully patched ISTA4.48.30.28287！

**Closed** 2024-07-26 03:11 UTC
